name: Maps Format checking
on: [push]
jobs:
  Maps-Format-Checking:
    runs-on: ubuntu-latest
    steps:
      - name: init job info
        run: echo "The job was triggered by a ${{ github.event_name }} event on branch ${{ github.ref }}"
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: execute py script$
        run: |
              python tests/maps-format.py
      - run: echo "Job status is ${{ job.status }}."

on:
  pull_request:
    types: [opened, reopened]
jobs:
  Maps-Format-Checking-PR:
    needs: [Maps-Format-Checking]
    runs-on: ubuntu-latest