name: Maps Format checking PR
on:
  pull_request:
    types: [opened, reopened]
jobs:
  Maps-Format-Checking-PR:
    needs: [Maps-Format-Checking]
    runs-on: ubuntu-latest
    steps:
      - name: init job info
        run: echo "The job was triggered by a ${{ github.event_name }} event on branch ${{ github.ref }}"