name: Maps Format checking
on: [push]
jobs:
  Maps-Format-Checking:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was triggered by a ${{ github.event_name }} event on branch ${{ github.ref }}"
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: execute py script$
        run: |
              python tests/maps-format.py
      - name: export index
      - run: echo "Job status is ${{ job.status }}."